import { useState, useEffect } from "react";
import { Button, Col, Container, Row } from "reactstrap";
import BreadcrumComp from "../../components/breadcrumComp";
import FilterCard from "../../components/searchComponents/filterCard";
import InstallmentCard from "../../components/searchComponents/Quote";
import SearchDropdownDiv from "../../components/searchComponents/searchDropdownDiv";
import { getAll_products } from "../../store/searchslice";
import { wrapper } from "../../store";
import { client } from "../../apollo-client";
import { gql } from "@apollo/client";
import { BiFilter } from "react-icons/bi";
import axios from "axios";
import NewsCard from "../../components/news/newsCard";
import BlogCard from "../../components/blogs/blogCard";
import Head from "next/head";
import { baseUrl } from '/env';

function Bloglist() {
  const [isMobile, setIsMobile] = useState(false);
  const [blogList, setBlogList] = useState();

  const handleResize = () => {
    if (window.innerWidth < 720) {
      setIsMobile(true);
    } else {
      setIsMobile(false);
    }
  };

  useEffect(() => {
    window.addEventListener("resize", handleResize);
  });

  useEffect(() => {
    axios
      .get(
        "${baseUrl}/api/homepage/getblogs"
      )
      .then((res) => {
        setBlogList(res.data.data);
      });
  }, []);

  return (
    <section className="white-bg-1 section pt-0 innernal-container2">
      <Head>
        <title>Blogs Nayagadi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Nayagadi_Icon.png" />
      </Head>
      <Container className="mt-4">
        <Row>
          {/* <Col className="col-12">
            <BreadcrumComp active_page={"Maruthi Vitara"} />NEWS
          </Col> */}

          <Col className="col-md-8 col-lg-9  mt-4 mt-lg-0">
            <div className="aside-right p-3">
              <h5>Latest Blogs</h5>
              {blogList &&
                blogList?.map((data, id) => {
                  return (
                    <div key={id}>
                      <BlogCard allBlogs={data} />
                    </div>
                  );
                })}
              <Row>
                <Button className="btn-ash">Load More Items</Button>
              </Row>
            </div>
          </Col>
          <Col className="col-lg-3 d-none d-sm-block d-lg-block">
            <div className="aside-left">
              <img src="../vb_1.jpg" />
            </div>
          </Col>
        </Row>
      </Container>
    </section>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    let brand = [""];
    let modals = [""];
    let car = [""];
    let fuel = [""];
    let min = "";
    let max = "";
    let query = context?.query?.slug ? context?.query?.slug[1] : null;
    if (query !== null && query?.includes("&")) {
      let arr = query.split("&");
      arr.forEach((q) => {
        let x = q.split("=");
      });
    }

    if (context?.query?.slug) {
      if (context?.query?.slug?.[0] == "bybudget") {
        const response = await axios.get(
          `${baseUrl}/api/products/searchProductsWithCarType?car_type=${query}&priceRange=${context?.query?.slug?.[2].trim()}`
        );
        store.dispatch(getAll_products(response.data));
      } else {
        const response = await axios.get(
          `${baseUrl}/api/products/getListOfProductNames?products_brand=${query}&productName=${context?.query?.slug?.[2].trim()}`
        );
        store.dispatch(getAll_products(response.data));
      }
    } else {
      const response = await axios.get(
        `${baseUrl}/api/products/getAllProducts`
      );
      store.dispatch(getAll_products(response.data));
    }
  }
);

export default Bloglist;
