import Price from "./price";
import Specs from "./spects";
import Vitara from "./vitara";
import CompareTab from "./compareTab.js";
import EmiModal from "../popupModal";
import ReactStars from "react-stars";
import Tab from "react-bootstrap/Tab";
import Tabs from "react-bootstrap/Tabs";
import ImageGallery from "react-image-gallery";
import "react-image-gallery/styles/css/image-gallery.css";
import { Col, Container, Row, Button, CardImg } from "reactstrap";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { BiVideo, BiAdjust } from "react-icons/bi";
import { FaSyncAlt } from "react-icons/fa";
import { numInLakh, priceFormat } from "../../priceformat";
import { baseImageurl } from "../../env";
import { emiimg } from "../../env";
import { FaCarAlt, FaPalette, FaStar } from "react-icons/fa";
import {
  BiCalculator,
  BiPencil,
  BiShieldQuarter,
  BiGitCompare,
} from "react-icons/bi";
import { Card, CardBody, CardFooter, CardHeader } from "reactstrap";
import Form from "react-bootstrap/Form";
import { Modal, ModalHeader, ModalBody, ModalFooter, Input } from "reactstrap";
import Gallery from "../../pages/gallery";
import { useSelector } from "react-redux";
import Head from "next/head";
import OverlayTrigger from "react-bootstrap/OverlayTrigger";
import Tooltip from "react-bootstrap/Tooltip";

function DetailsLayout({ product, variantsData }) {
  const [modal, setModal] = useState(false);
  const router = useRouter();
  const toggle = () => setModal(!modal);
  const images = [
    {
      original: product?.[0]?.Images?.images[0],
      thumbnail: product?.[0]?.Images?.images[0],
    },
  ];
  const [show, setShow] = useState(false);
  const [click, setClick] = useState("");

  const view = "360 view";
  const exterior = "exterior";
  const interior = "interior";
  const colors = "colors";
  const road = "road test";
  const video = "videos";
  //EMI CALUCALTIONS
  // const productPrice = useSelector((state) => state.searchproducts.productDetails?.[0]?.initialPrice);
  const [downpayment, setDownpayment] = useState(150000);
  const [bankinterest, setBankInterest] = useState(9.8);
  const [loanperiod, setLoanPeriod] = useState(5);
  const [price, setPrice] = useState(product?.[0]?.initialPrice);
  const [emicalculation, setEmicalculation] = useState({});
  const [ratingrmodal, setratingrmodal] = useState(false);
  const toggleratings = () => setratingrmodal(!ratingrmodal);
  useEffect(() => {
    setPrice(product?.[0]?.initialPrice);
  }, [product]);

  useEffect(() => {
    let latestPrice = price - downpayment;
    let InterestValue = (latestPrice * bankinterest * loanperiod) / 100;
    InterestValue.toFixed(2);
    let TotalAmount = InterestValue + latestPrice;
    TotalAmount.toFixed(2);
    let EMIAmount = TotalAmount / (loanperiod * 12);
    EMIAmount.toFixed(1);
    setEmicalculation({
      latestPrice: latestPrice,
      InterestValue: InterestValue,
      TotalAmount: TotalAmount,
      EMIAmount: EMIAmount,
    });
  }, [downpayment, bankinterest, loanperiod, price]);

  function showModel(value) {
    setShow(true);
    setClick(value);
  }
  //Share product functionality
  const handleShare = () => {
    // Check if navigator.share is supported by the browser
    if (navigator.share) {
      navigator
        .share({
          url: window.location.href,
          // url: `http://localhost:3000/${product?.[0]?.productBrands?.[0]?.BrandName}-${product?.[0].ProductName}/${product?.[0].id}`
        })
        .then(() => {
          // console.log("Sharing successfull");
        })
        .catch(() => {
          // console.log("Sharing failed");
        });
    } else {
      alert("Sorry! Your browser does not support Web Share API");
      // console.log("Sorry! Your browser does not support Web Share API");
    }
  };
  // Function to print page
  function print() {
    window.print();
  }
  // console.log(emicalculation, 'EEEEEEEEEEEEEEEEE')
  return (
    <>
      <Head>
        <title>{product?.[0]?.productBrands?.[0]?.BrandName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Nayagadi_Icon.png" />
      </Head>
      <style jsx>
        {`
          .tab_head {
            color: rgba(0, 0, 0, 0.5) !important;
          }

          .tab_head.active {
            border-bottom: 3px solid red;
            padding-bottom: 0;
          }
        `}
      </style>
      <Container className="product-details_page">
        <Row className="g-5 p-0">
          <Col lg="8">
            <Row className="bg-white my-3 py-3">
              <Row className="mb-2 title-card">
                <Col className=" col-12 col-sm-8">
                  <p className="m-0">{product?.[0]?.category}</p>
                  <h3 className="fw-500">
                    {product?.[0]?.productBrands?.[0]?.BrandName}{" "}
                    <span className="red">{product?.[0]?.ProductName}</span>
                  </h3>
                </Col>
                <Col
                  lg={2}
                  className="col-6 col-sm-2 border-end float-end justify-content-end"
                >
                  <p className="m-0 title-sides">
                    <b>PRICE</b>
                  </p>
                  <h3 className="m-0 mt-2 black title-sides-p justify-content-center">
                    {/* <b>
                    ₹ {numInLakh(product?.[0]?.initialPrice)} -{" "}
                    ₹ {numInLakh(product?.[0]?.finalPrice)}
                    </b> */}
                    <OverlayTrigger
                      placement="left"
                      overlay={
                        <Tooltip id="tooltip-disabled">
                          {" "}
                          {priceFormat(product?.[0]?.initialPrice)} -{" "}
                          {priceFormat(product?.[0]?.finalPrice)}
                        </Tooltip>
                      }
                    >
                      <span className="d-inline-block">
                        <div style={{ pointerEvents: "none" }}>
                          <label>
                            ₹{" "}
                            {numInLakh(product?.[0]?.initialPrice)?.slice(
                              0,
                              -1
                            )}{" "}
                            - {numInLakh(product?.[0]?.finalPrice)}
                          </label>
                        </div>
                      </span>
                    </OverlayTrigger>
                    <span className="red">*</span>
                  </h3>
                </Col>
                <Col
                  lg={2}
                  className="col-6 col-sm-2 d-grid justify-content-end"
                >
                  <p className="m-0 title-sides">
                    <b>Reviews</b>
                  </p>
                  <div
                    className="d-flex justify-content-center"
                    onClick={() => setratingrmodal(true)}
                  >
                    <ReactStars
                      count={5}
                      size={18}
                      color2={"#D01818"}
                      value={product?.[0]?.Review}
                    />
                    <label className="d-flex align-items-center ">
                      {" "}
                      {product?.[0]?.Review}
                    </label>
                  </div>
                </Col>
              </Row>

              <Row className="m-0 product-container p-0">
                <Col lg={10} className="gallery-container">
                  <ImageGallery
                    items={images}
                    slideOnThumbnailOver={true}
                    showNav={false}
                    showFullscreenButton={false}
                    showPlayButton={false}
                    showBullets={false}
                    thumbnailPosition={"left"}
                    className="mt-5 d-none"
                  />

                  <div className="strip-nav">
                    <Button
                      className="thumbnail-img-btn"
                      value="360view"
                      onClick={() => showModel(view)}
                    >
                      <div className="thumbnail-img">
                        <img src="/car3.png" />
                      </div>
                      <div className="content  d-flex">
                        <FaSyncAlt />

                        <span className="fs-10">360 View</span>
                      </div>
                    </Button>

                    <Button
                      className="thumbnail-img-btn"
                      onClick={() => showModel(exterior)}
                    >
                      <div className="thumbnail-img">
                        <img src="/car3.png" />
                      </div>
                      <div className="content">
                        <FaCarAlt />
                        <span className="fs-10">Exterior</span>
                      </div>
                    </Button>

                    {/* <Button
                            className="thumbnail-img-btn"
                            onClick={() => showModel(interior)}
                          >
                            <div className="thumbnail-img">
                              <img src="/car3.png" />
                            </div>
                            <div className="content">
                              <FaSyncAlt />
                              <span>Interior</span>
                            </div>
                          </Button> */}

                    <Button
                      className="thumbnail-img-btn"
                      onClick={() => showModel(colors)}
                    >
                      <div className="thumbnail-img">
                        <img src="/car3.png" />
                      </div>
                      <div className="content">
                        <FaPalette />
                        <span className="fs-10">Colors</span>
                      </div>
                    </Button>

                    {/* <Button
                            className="thumbnail-img-btn"
                            onClick={() => showModel(road)}
                          >
                            <div className="thumbnail-img">
                              <img src="/car3.png" />
                            </div>
                            <div className="content">
                              <FaSyncAlt />
                              <span>Road Test</span>
                            </div>
                          </Button> */}

                    <Button
                      className="thumbnail-img-btn"
                      onClick={() => showModel(video)}
                    >
                      <div className="thumbnail-img">
                        <img src="/car3.png" />
                      </div>
                      <div className="content">
                        <BiVideo />
                        <span className="fs-10">Videos</span>
                      </div>
                    </Button>

                    {/* <Button
                            className="thumbnail-img-btn thumbnail-img-btn_2"
                            onClick={() =>
                              router.push("/gallery#pills-colours")
                            }
                          >
                            <div className="thumbnail-img">
                              <img src="/car3.png" />
                            </div>
                            <div className="content">
                              <BiAdjust />
                              <span>Colors</span>
                            </div>
                          </Button> */}
                  </div>
                </Col>
                <Col className="text-end side-slider-spec wrap-overflow car-side-specs">
                  <div>
                    <p className="m-0 fw-500 sepc-headings mt-3">Engine</p>
                    <p className="fw-500  sepc-ranges">
                      <span className="h6">
                        {/* {product?.[0]?.EngineBasic}- */}
                        {product?.[0]?.EngineTopEnd}
                      </span>{" "}
                      <small className="black rang-extentions">CC</small>
                    </p>
                  </div>
                  <div>
                    <p className="m-0 mt-3 fw-500 sepc-headings">Max Power</p>
                    <p className="fw-500  sepc-ranges">
                      {/* {product?.[0]?.BHPBasic} */}
                      <span className="h6">{product?.[0]?.BHPTopEnd}</span>{" "}
                      <small className="black rang-extentions">BHP</small>
                    </p>
                  </div>
                  <div>
                    <p className="m-0 mt-3 fw-500 sepc-headings">Top Speed</p>
                    <p className="fw-500  sepc-ranges">
                      <span className="h4">{product?.[0]?.TopSpeed}</span>{" "}
                      <small className="black rang-extentions">KMPH</small>
                    </p>
                  </div>
                  <div>
                    <p className="m-0 mt-3 fw-500 sepc-headings">1-100 KMPH</p>
                    <p className="fw-500  sepc-ranges">
                      <span className="h4">{product?.[0]?.speedRange}</span>{" "}
                      <small className="black rang-extentions">SECS</small>
                    </p>
                    </div>
                  <div>
                    <p className="m-0 mt-3 fw-500 sepc-headings">
                      Fuel Economy
                    </p>
                    {/* <p className="fw-500">
                          City <span className="h4">{product?.[0]?.city}</span>{" "}
                          <small className="black">KMS</small>
                        </p> */}
                    <p className="fw-500 sepc-ranges">
                      {" "}
                      <span className="h4 kmp-number">
                        {product?.[0]?.highway}
                      </span>{" "}
                      <small className="black rang-extentions">KMPL</small>
                    </p>
                    <small className="black rang-extentions float-end">
                      (Highway)
                    </small>
                  </div>
                </Col>
              </Row>
              <Modal
                show={show}
                onHide={() => setShow(false)}
                aria-labelledby="example-custom-modal-styling-title"
                className="modal-popup"
              >
                <Modal.Header closeButton>
                  <Modal.Title id="example-custom-modal-styling-title modal-title-head">
                    {click}
                  </Modal.Title>
                </Modal.Header>
                {click === "colors" ? (
                  <Tabs
                    defaultActiveKey="blue"
                    id="uncontrolled-tab-example"
                    className="mb-3"
                    justify
                  >
                    <Tab
                      eventKey="blue"
                      style={{ color: "#ed2169" }}
                      title="Blue"
                    >
                      <Gallery forGallery={click} />
                    </Tab>
                    <Tab
                      eventKey="red"
                      style={{ color: "#ed2169" }}
                      title="Red"
                    >
                      <Gallery forGallery={click} />
                    </Tab>
                    <Tab
                      eventKey="white"
                      style={{ color: "#ed2169" }}
                      title="White"
                    >
                      <Gallery forGallery={click} />
                    </Tab>
                    <Tab
                      eventKey="black"
                      style={{ color: "#ed2169" }}
                      title="Black"
                    >
                      <Gallery forGallery={click} />
                    </Tab>
                    <Tab
                      eventKey="grey"
                      style={{ color: "#ed2169" }}
                      title="Grey"
                    >
                      <Gallery forGallery={click} />
                    </Tab>
                  </Tabs>
                ) : click === "videos" ? (
                  <Gallery forGallery={click} />
                ) : click === "exterior" ? (
                  <Tabs
                    defaultActiveKey="exterior"
                    id="uncontrolled-tab-example"
                    className="mb-3"
                    justify
                  >
                    <Tab
                      eventKey="exterior"
                      style={{ color: "#ed2169" }}
                      title="Exterior"
                    >
                      <Gallery forGallery={click} />
                    </Tab>
                    <Tab
                      eventKey="interior"
                      style={{ color: "#ed2169" }}
                      title="Interior"
                    >
                      <Gallery forGallery={click} />
                    </Tab>
                  </Tabs>
                ) : (
                  <Gallery forGallery={click} />
                )}
              </Modal>

              <Row className="m-0 p-0 mb-2">
                <hr className="mt-2 hr-product" />
                <Col className="text-end">
                  {/* <img
                      alt="pdf-icon"
                      className="mx-2"
                      src="../pdf-icon.svg"
                    /> */}
                  <img
                    alt="print-icon"
                    className="mx-2"
                    src="/print-icon.svg"
                    onClick={print}
                  />
                  {/*Hiding Wishlist as of now*/}
                  {/* <img
                      alt="like-icon"
                      className="mx-2"
                      src="../like-icon.svg"
                    /> */}
                  <img
                    alt="share-icon"
                    className="mx-2"
                    src="/share-icon.svg"
                    onClick={handleShare}
                  />
                </Col>
              </Row>
            </Row>

            <Row className="bg-white mt-3">
              <ul className="nav p-2" id="pills-tab" role="tablist">
                <li className="nav-item" role="presentation">
                  <a
                    className="nav-link tab_head active fw-bold"
                    id="pills-profile-tab"
                    href=""
                    data-bs-toggle="pill"
                    data-bs-target="#pills-profile"
                    role="tab"
                    aria-controls="pills-profile"
                    aria-selected="false"
                  >
                    {" "}
                    SPECIFICATIONS
                  </a>
                </li>
                <li className="nav-item" role="presentation">
                  <a
                    className="nav-link tab_head fw-bold"
                    id="pills-contact-tab"
                    href=""
                    data-bs-toggle="pill"
                    data-bs-target="#pills-contact"
                    role="tab"
                    aria-controls="pills-contact"
                    aria-selected="false"
                  >
                    PRICE
                  </a>
                </li>
                <li className="nav-item" role="presentation">
                  <a
                    className="nav-link tab_head fw-bold"
                    id="pills-compare-tab"
                    href=""
                    data-bs-toggle="pill"
                    data-bs-target="#pills-compare"
                    role="tab"
                    aria-controls="pills-compare"
                    aria-selected="false"
                  >
                    COMPARE MODEL
                  </a>
                </li>
                <li className="nav-item" role="presentation">
                  <a
                    className="nav-link tab_head fw-bold"
                    id="pills-home-tab"
                    href=""
                    data-bs-toggle="pill"
                    data-bs-target="#pills-home"
                    role="tab"
                    aria-controls="pills-home"
                    aria-selected="true"
                  >
                    DETAILS
                  </a>
                </li>
              </ul>
            </Row>

            <Row className="mt-3">
              <div className="tab-content p-0" id="pills-tabContent">
                <div
                  className="tab-pane p-0 fade show active"
                  id="pills-profile"
                  role="tabpanel"
                  aria-labelledby="pills-profile-tab"
                >
                  <Specs product={product} />
                </div>
                <div
                  className="tab-pane p-0 fade"
                  id="pills-contact"
                  role="tabpanel"
                  aria-labelledby="pills-contact-tab"
                >
                  <Price
                    product={product}
                    EMIAmount={emicalculation?.EMIAmount}
                    variantsData={variantsData}
                  />
                </div>
                <div
                  className="tab-pane p-0 fade"
                  id="pills-compare"
                  role="tabpanel"
                  aria-labelledby="pills-compare-tab"
                >
                  <CompareTab product={product} variantsData={variantsData} />
                </div>
                <div
                  className="tab-pane fade"
                  id="pills-home"
                  role="tabpanel"
                  aria-labelledby="pills-home-tab"
                >
                  <Vitara product={product} />
                </div>
                <div
                  className="tab-pane p-0 fade"
                  id="pills-more"
                  role="tabpanel"
                  aria-labelledby="pills-more-tab"
                >
                  <p>Fifth</p>
                </div>
              </div>
            </Row>
            {/* <Row className="bg-white mt-3 py-4">
                <h5>
                  {product?.[0]?.attributes?.car_features?.data?.map(
                    (features, id) => {
                      return (
                        <div key={id}>
                          <ul className="features-list">
                            <li>
                              <BiVideo />
                              {features?.attributes?.Features}
                            </li>
                          </ul>
                        </div>
                      );
                    }
                  )}
                </h5>
              </Row> */}
          </Col>
          <Col lg="4" className="emi-container">
            <Row className="px-3 p-2 bg-white mt-3">
              <div className=" m-0 p-0 gap-2 d-flex justify-content-between price-btns">
                <Button
                  className="btn-red btn-product-emi my-2"
                  size="lg"
                  onClick={() => setModal(true)}
                >
                  <BiCalculator className="fs-22" />
                  <span>EMI CALCULATOR</span>
                </Button>
                <Button className="btn-black btn-product-emi my-2" size="lg">
                  <BiShieldQuarter className="fs-22" />
                  <span>INSURANCE</span>
                </Button>
              </div>
              <Card className="emi-card my-2">
                <CardBody>
                  <Row>
                    <Col className="col-7  p-0 m-0 ">
                      <h5 className="m-0 text-white fw-400">EMI Details </h5>
                      <h5 className="m-0 mt-2  d-flex align-items-center pencil-btn">
                        <button className="emi-pencil-btn">
                          <BiPencil
                            className="btn-icons"
                            onClick={() => setModal(true)}
                          />
                        </button>
                        <label className="amt">
                          {" "}
                          <span className="fs-18"></span>
                          {
                            priceFormat(emicalculation?.EMIAmount)?.split(
                              "."
                            )[0]
                          }
                          <span className="fs-13">/Month</span>{" "}
                        </label>
                      </h5>
                    </Col>
                    <Col className="m-0 p-0 ">
                      <div>
                        <CardImg src="/emiimg.svg" className="" />
                      </div>
                    </Col>
                  </Row>
                  <h6 className="fs-13 mt-1">
                    Interest calculated on {priceFormat(price)?.split(".")[0]}{" "}
                    /-
                    <br></br>starts at 9.8% for 60 months{" "}
                  </h6>
                </CardBody>
                <Button className="btn-knowmore mb-2" size="lg">
                  <span> Find More Finance companies</span>
                </Button>
              </Card>
              <img src="/car_add.jpg" className="p-0 my-2" />
            </Row>
          </Col>
        </Row>
      </Container>

      <EmiModal
        product={product}
        open={modal}
        toggle={toggle}
        backdrop={true}
      />
      {/* Ratings modals starts hear */}
      <Modal isOpen={ratingrmodal} className="rating-modal">
        <ModalHeader toggle={toggleratings}></ModalHeader>
        <ModalBody>
          <div className="top_icons_container">
            <div className="borucher-form">
              <h4>Rate & Review</h4>
              <p>
                Tell us about your buying experience and why you shortlisted
                this car
              </p>
              {/* car Details starts hear */}
              <Row className="d-flex">
                <Col className="col-5">
                  <div className="rating-car-img">
                    <img src="/car3.png" className="p-0 my-2" />
                  </div>
                </Col>
                <Col>
                  <h5>Brand</h5>
                  <h6>Car Name</h6>
                  <p>Petrol/Ev/Desil</p>
                </Col>
                <Col className="ratting-side-div col-2">
                  <FaStar className="stars" />
                  <h5>
                    <b>2.5</b>
                  </h5>
                  <p>Overall Rating</p>
                </Col>
              </Row>

              <Form
                validate="true"
                onSubmit={(e) => SubmitForm(e)}
                className="mt-2"
              >
                {/* Smily ratings starts hear */}
                <div className="star-ratings">
                <Row className="d-flex ">
                  <Col className="col-4 col-sm-4 col-lg-4">
                    <h5>Mileage</h5>
                  </Col>
                  <Col>
                    <div class="image_radio_button_control">
                      <label class="radio-button-label">
                        <input
                          type="radio"
                          name="radio-control"
                          className="radio-input"
                          value="lsb"
                        />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="nosb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsab" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rasb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                    </div>

                    {/*             
              <Form.Group className="FormGroup">
                    <Form.Label check className="mb-2">
                      <Input
                        id="checkId"
                        className="form-controlz"
                        type="checkbox"
                        name="accepted"
                      /> &nbsp;
                      <img src="/smily-1.svg" className="p-0 my-2" />
                    </Form.Label>
                  </Form.Group> */}
                  </Col>
                </Row>
                <Row className="d-flex mt-3">
                  <Col className="col-4">
                    <h5>Maintenance Cost</h5>
                  </Col>
                  <Col>
                    <div class="image_radio_button_control">
                      <label class="radio-button-label">
                        <input
                          type="radio"
                          name="radio-control"
                          className="radio-input"
                          value="lsb"
                        />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="nosb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsab" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rasb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                    </div>

                    {/*             
              <Form.Group className="FormGroup">
                    <Form.Label check className="mb-2">
                      <Input
                        id="checkId"
                        className="form-controlz"
                        type="checkbox"
                        name="accepted"
                      /> &nbsp;
                      <img src="/smily-1.svg" className="p-0 my-2" />
                    </Form.Label>
                  </Form.Group> */}
                  </Col>
                </Row>
                <Row className="d-flex mt-3">
                  <Col className="col-4">
                    <h5>Safety  </h5>
                  </Col>
                  <Col>
                    <div class="image_radio_button_control">
                      <label class="radio-button-label">
                        <input
                          type="radio"
                          name="radio-control"
                          className="radio-input"
                          value="lsb"
                        />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="nosb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsab" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rasb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                    </div>

                    {/*             
              <Form.Group className="FormGroup">
                    <Form.Label check className="mb-2">
                      <Input
                        id="checkId"
                        className="form-controlz"
                        type="checkbox"
                        name="accepted"
                      /> &nbsp;
                      <img src="/smily-1.svg" className="p-0 my-2" />
                    </Form.Label>
                  </Form.Group> */}
                  </Col>
                </Row>
                <Row className="d-flex mt-3">
                  <Col className="col-4">
                    <h5>Features & Styling</h5>
                  </Col>
                  <Col>
                    <div class="image_radio_button_control">
                      <label class="radio-button-label">
                        <input
                          type="radio"
                          name="radio-control"
                          className="radio-input"
                          value="lsb"
                        />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="nosb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsab" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rasb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                    </div>

                    {/*             
              <Form.Group className="FormGroup">
                    <Form.Label check className="mb-2">
                      <Input
                        id="checkId"
                        className="form-controlz"
                        type="checkbox"
                        name="accepted"
                      /> &nbsp;
                      <img src="/smily-1.svg" className="p-0 my-2" />
                    </Form.Label>
                  </Form.Group> */}
                  </Col>
                </Row>
                <Row className="d-flex mt-3">
                  <Col className="col-4">
                    <h5>Comfort    </h5>
                  </Col>
                  <Col>
                    <div class="image_radio_button_control">
                      <label class="radio-button-label">
                        <input
                          type="radio"
                          name="radio-control"
                          className="radio-input"
                          value="lsb"
                        />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="nosb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsab" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rasb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                    </div>

                    {/*             
              <Form.Group className="FormGroup">
                    <Form.Label check className="mb-2">
                      <Input
                        id="checkId"
                        className="form-controlz"
                        type="checkbox"
                        name="accepted"
                      /> &nbsp;
                      <img src="/smily-1.svg" className="p-0 my-2" />
                    </Form.Label>
                  </Form.Group> */}
                  </Col>
                </Row>
                <Row className="d-flex mt-3">
                  <Col className="col-4">
                    <h5>Performance  </h5>
                  </Col>
                  <Col>
                    <div class="image_radio_button_control">
                      <label class="radio-button-label">
                        <input
                          type="radio"
                          name="radio-control"
                          className="radio-input"
                          value="lsb"
                        />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="nosb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>

                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rsab" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                      <label class="radio-button-label">
                        <input type="radio" name="radio-control" value="rasb" />
                        <img className="radio-img" src="/smily-1.svg" />
                      </label>
                    </div>

                    {/*             
              <Form.Group className="FormGroup">
                    <Form.Label check className="mb-2">
                      <Input
                        id="checkId"
                        className="form-controlz"
                        type="checkbox"
                        name="accepted"
                      /> &nbsp;
                      <img src="/smily-1.svg" className="p-0 my-2" />
                    </Form.Label>
                  </Form.Group> */}
                  </Col>
                </Row>
                </div>

                <Form.Group className="mb-3" controlId="formBasicPassword">
                  <Form.Label>
                    Name <span class="red">*</span>
                  </Form.Label>
                  <Form.Control
                    type="text"
                    placeholder="Enter Name"
                    required
                    name="name"
                  />
                </Form.Group>
                <Row>
                  <Col>
                    <Form.Group className="mb-3" controlId="formBasicPassword">
                      <Form.Label>
                        Email Id <span class="red">*</span>
                      </Form.Label>
                      <Form.Control
                        type="number"
                        placeholder="Enter Email id"
                        required
                        name="phone"
                      />
                    </Form.Group>
                  </Col>
                  <Col>
                    <Form.Group className="mb-3" controlId="formBasicPassword">
                      <Form.Label>
                        Phone Number <span class="red">*</span>
                      </Form.Label>
                      <Form.Control
                        type="number"
                        placeholder="Enter Mobile Number"
                        required
                        name="phone"
                      />
                    </Form.Group>
                  </Col>
                </Row>
                <Form.Group className="mb-3" controlId="formBasicEmail">
                  <Form.Label>Message</Form.Label>
                  <Form.Control
                    type="textarea"
                    placeholder="Message"
                    required
                    name="city"
                    as="textarea"
                    rows={3}
                  />
                </Form.Group>
                <Button
                  type="submit"
                  className="btn-red btn-product-emi my-2 btn btn-secondary btn-lg"
                >
                  <a href={product?.[0]?.brochure} download></a>
                  Submit
                </Button>
              </Form>
              {/* after the form submittion */}
              <div className="d-flex">
                <img src="/check.svg" />
                <h4>Thanks for your interest in Hyundai Creta</h4>
              </div>
              <div className="whats-app p-4 mt-3">
                <img src="/wapp.svg" />
                <p>
                  Thank You! We would keep you updated on latest cars and offers
                  through Whatsapp
                </p>
              </div>
            </div>
          </div>
        </ModalBody>
      </Modal>
    </>
  );
}

export default DetailsLayout;
