import { aboutus } from "../store/footerSlice";
import { useSelector } from "react-redux";
import { wrapper } from "../store";
import { client } from "../apollo-client";
import { gql } from "@apollo/client";
// import '../styles/globals.scss'
import Innerbanner from "../components/Innerbanner";

import {
  Col,
  Row,
  Container,
  Card,
  CardBody,
  CardTitle,
  CardSubtitle,
  CardText,
  Button,
} from "reactstrap";
import { useState, useEffect } from "react";
import axios from "axios";
import Head from "next/head";
import { baseUrl } from "../env";
export default function Aboutus() {
  const [about, setAbout] = useState([]);

  useEffect(() => {
    axios.get(`${baseUrl}/api/homepage/getAboutus`).then((response) => {
      setAbout(response?.data?.data[0]);
    });
  }, []);
  //https://www.slntechnologies.com/wp-content/uploads/2017/08/ef3-placeholder-image.jpg
  return (
    <div>
      <Innerbanner />
      <section className="white-bg section">
        <Head>
          <title>Nayagadi</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Nayagadi_Icon.png" />
        </Head>
        <Container>
          <Row>
            <Col xs="6">
              <div className="innernal-container new-news-card">
                <h3>ABOUT US</h3>
                <h6>
                  Every Thing You Need To Build an Amazing DealerShip automotive
                  responsive website
                </h6>
                {about?.content ? (
                  <p>{about?.content}</p>
                ) : (
                  <div className="spinner">
                    <div class="loading-bar"></div>
                  </div>
                )}
              </div>
            </Col>
            <Col xs="6">
              <div className="innernal-container new-news-card">
                <img
                  src={about?.landingimage}
                  style={{ width: "650px", height: "400px" }}
                />
              </div>
            </Col>
          </Row>
        </Container>
        <Container>
          <Row>
            {/* <Col xs="3">
            <Card
              style={{
                width: '18rem',"box-shadow": "0px 0px 0px rgb(0 0 0 / 9%)"

              }}
            >
              <img className="aboutcardimage"
                alt="Sample"
                src="https://happimobiles.s3.ap-south-1.amazonaws.com/test-images/carkeys-removebg-preview.png" 
              />
              <CardBody style={{"height":"150px"}}>
                <CardTitle tag="h5" style={{"position": "relative","top": "20px"}}>
                  DealerShip
                </CardTitle>
               
                <CardText style={{"position": "relative","top": "40px"}}>
                  We have the right caring,experience and dedicated professional for you
                </CardText>
              
              </CardBody>
            </Card>
          </Col> */}
            <Col xs="3">
              <Card className="about-us-card">
                <img
                  className="aboutcardimage"
                  alt="Sample"
                  src="https://happimobiles.s3.ap-south-1.amazonaws.com/test-images/carkeys-removebg-preview.png"
                />
                <CardBody>
                  <CardTitle>
                    <h6>DealerShip</h6>
                  </CardTitle>

                  <CardText className="mt-4">
                    We have the right caring,experience and dedicated
                    professional for you
                  </CardText>
                </CardBody>
              </Card>
            </Col>
            <Col xs="3">
              <Card className="about-us-card">
                <img
                  className="aboutcardimage"
                  alt="Sample"
                  src="https://happimobiles.s3.ap-south-1.amazonaws.com/test-images/carkeys-removebg-preview.png"
                />
                <CardBody>
                  <CardTitle>
                    <h6>DealerShip</h6>
                  </CardTitle>

                  <CardText className="mt-4">
                    We have the right caring,experience and dedicated
                    professional for you
                  </CardText>
                </CardBody>
              </Card>
            </Col>
            <Col xs="3">
              <Card className="about-us-card">
                <img
                  className="aboutcardimage"
                  alt="Sample"
                  src="https://happimobiles.s3.ap-south-1.amazonaws.com/test-images/carkeys-removebg-preview.png"
                />
                <CardBody>
                  <CardTitle>
                    <h6>DealerShip</h6>
                  </CardTitle>

                  <CardText className="mt-4">
                    We have the right caring,experience and dedicated
                    professional for you
                  </CardText>
                </CardBody>
              </Card>
            </Col>
            <Col xs="3">
              <Card className="about-us-card">
                <img
                  className="aboutcardimage"
                  alt="Sample"
                  src="https://happimobiles.s3.ap-south-1.amazonaws.com/test-images/carkeys-removebg-preview.png"
                />
                <CardBody>
                  <CardTitle>
                    <h6>DealerShip</h6>
                  </CardTitle>

                  <CardText className="mt-4">
                    We have the right caring,experience and dedicated
                    professional for you
                  </CardText>
                </CardBody>
              </Card>
            </Col>
          </Row>
        </Container>
      </section>
    </div>
  );
}
