import { useState, useEffect } from "react";
import { Button, Col, Container, Row } from "reactstrap";
import axios from "axios";
import BlogCard from "../components/blogs/blogCard";
import Head from "next/head";
import Form from "react-bootstrap/Form";
import InputGroup from "react-bootstrap/InputGroup";
import {
  BiListUl, BiGridAlt, BiMailSend,
  BiSearch,
  BiGridSmall,
  BiChevronsRight,
  BiCalendarAlt,
} from "react-icons/bi";
import { baseUrl } from '../env';
import { wrapper } from "/store";
import Pagination from "../components/Pagination";

function Blogs(blogs) {
  const [isMobile, setIsMobile] = useState(false);
  const [gridView, setGridView] = useState(false);
  const [totalproducts, setTotalProducts] = useState();
  const [latestblogs, setLatestBlogs] = useState([]);
  const [trendingblogs, setTrendingBlogs] = useState([]);
  const blogList = blogs?.blogs?.data;
  const noOfProducts = blogs?.blogs?.TotalBlogs;
  const handleResize = () => {
    if (window.innerWidth < 720) {
      setIsMobile(true);
    } else {
      setIsMobile(false);
    }
  };

  useEffect(() => {
    window.addEventListener("resize", handleResize);
  });

  useEffect(() => {
    axios
      .get(
        `${baseUrl}/api/products/noOfProductsBasedOnCategory`
      )
      .then((res) => {
        setTotalProducts(res.data.data)
      });
  }, []);
  useEffect(() => {
    axios
      .get(
        `${baseUrl}/api/blogs/latestblogs`
      )
      .then((res) => {
        setLatestBlogs(res.data.data)
      });
  }, []);
  useEffect(() => {
    axios
      .get(
        `${baseUrl}/api/blogs/trendingblogs`
      )
      .then((res) => {
        setTrendingBlogs(res.data.data)
      });
  }, []);

  return (
    <section className="white-bg-1 section pt-0 innernal-container2 mb-4">
      <Head>
        <title>Blogs Nayagadi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Nayagadi_Icon.png" />
      </Head>
      <Container className="mt-4">
        <Row>
          {/* <Col className="col-12">
            <BreadcrumComp active_page={"Maruthi Vitara"} />NEWS
          </Col> */}
          <Col className="col-md-8 col-lg-9 mt-4 mt-lg-0">
            <div className="aside-left p-3">
              <Row>
                <Col lg="10" className="mt-2 d-flex align-items-center">
                  <h5>Latest Blogs</h5>
                </Col>
                <Col lg="2" className="mt-2 d-flex align-items-center">
                  <Button
                    className={!gridView ? ' ml-3 my-2 grid-highlight' : 'grid-icon-btns ml-3 my-2 '}
                    size="lg"
                    onClick={() => setGridView(false)}
                  >
                    <BiListUl />
                  </Button>
                  <Button
                    className={gridView ? 'ml-3 my-2 grid-highlight' : 'grid-icon-btns ml-3 my-2 '}
                    size="lg"
                    onClick={() => setGridView(true)}
                  >
                    <BiGridAlt />
                  </Button>
                </Col>
              </Row>
              {blogList ? (
                blogList?.map((data, id) => {
                  return (
                    <div key={id}>
                      <BlogCard allBlogs={data} gridview={gridView} />
                    </div>
                  );
                })
              ) : (
                <div className="spinner">
                  <div class="loading-bar"></div>
                </div>
              )}
            </div>
            <Row className="mb-4">
              <Col className="col-12 col-lg-12">
                {/* <Button className="btn-ash w-100">Load More Items</Button> */}
                <Pagination noOfProducts={noOfProducts} />
              </Col>
            </Row>
          </Col>
          {/* right side pannel-------------------------------- */}
          <Col className="col-lg-3 d-none d-sm-block d-lg-block">
            <div className="aside-right p-3">
              <div>
                <h4 className="bottom-line mb-2">Search By</h4>
                <InputGroup className="mb-3 search-input-text">
                  <Form.Control
                    placeholder="Search here"
                    aria-label="Username"
                    aria-describedby="basic-addon1"
                  />
                  <button className="blog-search">
                    <InputGroup.Text id="basic-addon1">GO</InputGroup.Text>
                  </button>
                </InputGroup>
              </div>
              {/* Categories starts hear -------------------------------- */}
              <div className="mt-4">
                <h4 className="bottom-line mb-2">Categories</h4>
                <div className="p-3">
                  <h4 className="sub-categories mb-2">
                    {" "}
                    <BiChevronsRight className="fs-18" /> Cars <span>({totalproducts})</span>
                  </h4>
                  <h4 className="sub-categories mb-2">
                    {" "}
                    <BiChevronsRight className="fs-18" /> Bikes{" "}
                    <span>(50)</span>
                  </h4>
                  <h4 className="sub-categories mb-2">
                    {" "}
                    <BiChevronsRight className="fs-18" /> Heavy vehicles{" "}
                    <span>(50)</span>
                  </h4>
                </div>
              </div>
              {/* Latest Blogs--------------- */}
              <div className="mt-3">
                <h4 className="bottom-line mb-2">Latest Posts</h4>
                <div className="p-2">
                  {/* latest blog details list view ------------*/}
                  {
                    latestblogs?.map((data, index) => {
                      return (
                        <div key={index}>
                          <Row className="mb-3">
                            <Col className="col-4 ">
                              <div className="post-img">
                                <img src={data?.blog_image} />
                              </div>
                            </Col>
                            <Col className="col-8 p-0">
                              <h4 className="post-heading">{data?.short_text}</h4>
                              <div className="pt-1">
                                <h4 className="post-date d-flex">
                                  <BiCalendarAlt className="callender-icon" />
                                  {new Date(data?.date).toLocaleDateString('en-us', { day: 'numeric', year: "numeric", month: "short" })}
                                </h4>
                              </div>
                            </Col>
                          </Row>
                        </div>
                      )

                    })
                  }
                  <div className="blog-add">
                    <img src="../car_add.jpg" />
                  </div>
                </div>
              </div>
              {/* Trending  Blogs--------------- */}
              <div className="mt-3">
                <h4 className="bottom-line mb-2">Trending Now</h4>
                <div className="p-2">
                  {/* latest blog details list view ------------*/}
                  {trendingblogs?.map((trendingblogsdata, index) => {
                    return (
                      <div key={index}>
                        <Row className="mb-3">
                          <Col className="col-4">
                            <div className="post-img">
                              <img src={trendingblogsdata?.blog_image} />
                            </div>
                          </Col>
                          <Col className="col-8 p-0">
                            <h4 className="post-heading">{trendingblogsdata?.short_text}</h4>
                            <div className="pt-1">
                              <h4 className="post-date d-flex">
                                <BiCalendarAlt className="callender-icon" />

                                {new Date(trendingblogsdata?.date).toLocaleDateString('en-us', { day: 'numeric', year: "numeric", month: "short" })}
                              </h4>
                            </div>
                          </Col>
                        </Row>
                      </div>
                    )
                  })}
                </div>
              </div>
              {/* News letter--------------- */}
              <div className="mt-3 newsletter">
                <h4 className="bottom-line mb-2">Blogs Letter Subscribe</h4>
                <div className="p-2">
                  <InputGroup className="mb-3">
                    <InputGroup.Text id="basic-addon1"><BiMailSend className="black fs-18" /></InputGroup.Text>
                    <Form.Control
                      placeholder="Enter Your email to "
                      aria-label="Username"
                      aria-describedby="basic-addon1" />
                  </InputGroup>
                  <Button
                    className="btn-red btn-news-subscribe fs-13 "
                    size="md"
                  >
                    <span>SUBSCRIBE NOW</span>
                  </Button>
                </div>
              </div>
              {/* <img src="../vb_1.jpg" /> */}
            </div>
          </Col>
        </Row>
      </Container>
    </section>
  );
}

// api for get blogs list
export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    const response = await axios.get(`${baseUrl}/api/homepage/getblogs?page=${context.query.page}`);
    let blogs = response.data;
    return {
      props: { blogs }
    }
  }
);

export default Blogs;
