import { Col, Row, Container,Card, CardBody, CardFooter, CardHeader  } from "reactstrap";
import React, { useEffect, useState } from "react";
import axios from "axios";
import Head from "next/head";
import { baseUrl } from '../env';
import Accordion from 'react-bootstrap/Accordion';
import Innerbanner from '../components/Innerbanner';

export default function Faqs() {
  const [FAQSData, setFAQSData] = useState([]);
  useEffect(() => {
    axios
      .get(
        `${baseUrl}/api/homepage/getfaqs`
      )
      .then((faqsresponse) => {
        setFAQSData(faqsresponse?.data?.data);
      });
  }, []);
  return (
    <>
        <div>
     <Innerbanner/>
      <section className=" section">
        <Head>
          <title>Nayagadi</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Nayagadi_Icon.png" />
        </Head>
        <Container>
          <Row>
            <Col className="col-8 white-bg">
             
              <div className="innernal-container faqs new-news-card ">
              <h4 className="bottom-line mb-3">Frequently Asked Questions</h4>
              <Card className="p-3 mb-3">
                <h4 className="bottom-line mb-3">What is NayaGadi</h4> 
                <CardBody className="p-0">
                  <div >
                    <h5>
                    WHAT MADE EACH OF THESE PEOPLE SO SUCCESSFUL?
                    </h5>
                    <p>Motivation is not an accident or something that someone else can give you — you are the only one with the power to motivate you. Motivation cannot be an external force, it must come from within as the natural product of your desire to achieve something and your belief that you are </p>
                      <ol>
                        <li>
                          There is a significant portion of the population here in North America.
                        </li>
                        <li>
                          There is a significant portion of the population here in North America.
                        </li>
                        <li>
                          There is a significant portion of the population here in North America.
                        </li>
                      </ol> 
                  </div>
                </CardBody>
              </Card>
                {FAQSData ? (
                  FAQSData?.map((item, id) => {
                    return (
                      // eslint-disable-next-line react/jsx-key
                      <Accordion>
                      <Accordion.Item eventKey="0">
                        <Accordion.Header><h5>{item.question}</h5></Accordion.Header>
                        <Accordion.Body className="p-2">
                          <p>{item.answer}</p>
                        </Accordion.Body>
                      </Accordion.Item>
                  </Accordion>
                    );
                  })
                ) : (
                  <div className="spinner">
                    <div class="loading-bar"></div>
                  </div>
                )}
              </div>
            </Col>
            <Col className="col-lg-3 d-none d-sm-block d-lg-block">
            <div className="aside-right p-3 white-bg">
            <div className="blog-add">
                    <img src="../car_add.jpg" />
                  </div>
              </div>

            </Col>
          </Row>
        </Container>
      </section>
      </div>
    </>
  );
}

{/* <div key={id} className="pt-1 pb-2">
<h6>
  {id + 1}.{item.question}
</h6>
<p>A.{item.answer}</p>
</div> */}

// export const getServerSideProps = wrapper.getServerSideProps(
//   (store) => async () => {
//     const { data } = await client.query({
//       query: gql`
//       query{
//         faqs{
//           data{
//             id
//             attributes{
//               Question
//               Answer
//               category
//               sort_index
//             }
//           }
//         }
//       }
//       `
//     });
//     store.dispatch(getFaqs(data));
//   }
// );
