import { useState, useEffect } from "react";
import { Button, Col, img, Container, Row } from "reactstrap";
import axios from "axios";
import NewsCard from "../components/news/newsCard";
import Head from 'next/head';
import Form from "react-bootstrap/Form";
import InputGroup from "react-bootstrap/InputGroup";
import Sidefilters from "../components/sidefilters/Sidefilters";
import {
  BiListUl, BiGridAlt,
  BiSearch,
  BiGridSmall,
  BiChevronsRight,
  BiCalendarAlt,
} from "react-icons/bi";
import { baseUrl } from '../env';
import { wrapper } from "/store";
import Pagination from '../components/Pagination'

function News(news) {
  const [isMobile, setIsMobile] = useState(false);
  const [gridView, setGridView] = useState(false);
  const newsList = news?.news?.data;
  const noOfProducts = news?.news?.TotalNews;
  const handleResize = () => {
    if (window.innerWidth < 720) {
      setIsMobile(true)
    } else {
      setIsMobile(false)
    }
  }

  useEffect(() => {
    window.addEventListener("resize", handleResize)
  })

 
  return (

    <section className="white-bg-1 section pt-0 innernal-container2">
      <Head>
        <title>Latest News Nayagadi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Nayagadi_Icon.png" />
      </Head>
      <Container className="mt-4">
        <Row>
          {/* <Col className="col-12">
            <BreadcrumComp active_page={"Maruthi Vitara"} />NEWS
          </Col> */}

          <Col className="col-md-8 col-lg-9 mt-4 mt-lg-0">
            <div className='aside-left p-3'>
              <Row>
                <Col lg="10" className="mt-2 d-flex align-items-center">
                  <h5>Latest News</h5>
                </Col>
                <Col lg="2" className="mt-2 d-flex align-items-center">
                  <Button
                    className={!gridView ? ' ml-3 my-2 grid-highlight' : 'grid-icon-btns ml-3 my-2 '}
                    size="lg"
                    onClick={() => setGridView(false)}
                  >
                    <BiListUl />
                  </Button>

                  <Button
                    className={gridView ? 'ml-3 my-2 grid-highlight' : 'grid-icon-btns ml-3 my-2 '}
                    size="lg"
                    onClick={() => setGridView(true)}
                  >
                    <BiGridAlt />
                  </Button>
                </Col>
              </Row>              {newsList ? newsList?.map((data, id) => {
                return (
                  <div key={id}>
                    <NewsCard allNews={data} gridView={gridView} />
                  </div>
                )
              }) : <div className='spinner'><div class="loading-bar"></div></div>}
            </div>
            <Row>
              {/* <Button className="btn-ash" >Load More Items</Button> */}
              <Pagination noOfProducts={noOfProducts} />
            </Row>
          </Col>
          <Col className="col-lg-3 d-none d-sm-block d-lg-block">
            <div className="aside-right p-1">
              <Sidefilters />
            </div>
          </Col>
        </Row>
      </Container>
    </section>
  )
}
// api for get blogs list
export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async (context) => {
    const response = await axios.get(`${baseUrl}/api/homepage/getnews?page=${context.query.page}`);
    let news = response.data;
    return {
      props: { news }
    }
  }
);

export default News;